### PR TITLE
Fixed the directories that had a space in the end, as well as directories

### PR DESCRIPTION
**Pull request by MinaSelim**
Fixed the directories that had a space in the end, as well as directories that ended with a dot.

### CODE REVIEW

**Comment by MinaSelim** [comment]
> These directory names still appear to have spaces in them, what exactly did you fix?

.../Assignments /Assignment 1/P1-7090323.rar → ...3/Assignments/Assignment 1/P1-7090323.rar

I will put the space I removed between  brackets:

.../Assignments[ ]/Assignment 1/P1-7090323.rar → ...3/Assignments/Assignment 1/P1-7090323.rar

**Comment by jhubscher** [comment]
Also, please install git on your computer and learn how to make a commit instead of downloading the entire repository and then re-uploading it,.

This is very inefficient.
If you changed the names of 10 files or folders lets say, I should be re-merging the _entire_ repository.

Here is a good starting point:
https://git-scm.com/book/en/v2

I will keep this issue open for now so that you may learn git and make a commit with a commit message containing the issue #2 in your commit message.

Hope this helps.

**Comment by MinaSelim** [comment]
I am not too sure what you are talking about, I forked the repo, did a clone locally and it failed near the end due to the illegal spaces in the directory ending, so I had to manually download the files that failed to clone so I can fix their pathing. There were multiple broken files, not just the Coen files, all the changed files were broken files that failed to clone due to pathing issues. for the Engr202 audio files, in windows it is illegal to end a directory with a dot

**Comment by MinaSelim** [comment]
I think you may be confused into thinking you are merging an entire repo into yours.

To let you know, git always merges a group of commits. in this case you are merging one commit that contains changes to 61 files (which are renames of the directory they are in).

**Comment by jhubscher** [comment]
Ah yes, I did get that impression. My apologies.

On another note, I am looking at COEN 243 for instance. Assignment 1 directory has a space in it, but the new committed name looks identical. I'm not seeing the fix for this one and other similarly named folders and yet they are in the commit.

Could you clarify that for me please?

**Comment by jhubscher** [comment]
Okay I'm seeing the end spaces for the SOEN 385 and COEN 243 directories, those were difficult for my eyes to catch.

I'm just gonna verify the ENGR 202 audio folder name as you mentioned and close this issue.

Thanks so much for your efforts!

**Pull request merged**
